name: mkdocs

on:
  push:
    branches:
      - main
      - docs

permissions:
  contents: write
  
jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./docs/setup-docs/requirements.txt
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
