name: Nextron CI

on:
  pull_request_target:

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true
  build:
    name: Django build
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - run: true