name: Nextron CI

on:
  pull_request_target:

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build:
    name: Build 
    strategy:
      matrix:
        include:
          - platform: mac
            os: "macos-12"
          - platform: linux
            os: "ubuntu-22.04"
          - platform: windows
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    needs: authorize
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 14
      
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --network-timeout 1000000  # will run `yarn install` command
          dir: desktop-app

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command (for each os)
          dir: desktop-app
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-distributables
          path: desktop-app/dist/Napse-*
          if-no-files-found: error

