name: Nextron CI

on:
  pull_request_target:

jobs:
  authorize:
    environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build:
    name: Build 
    strategy:
      matrix:
        include:
          - platform: linux
            os: "ubuntu-22.04"
          - platform: windows
            os: "windows-2022"
          - platform: mac
            os: "macos-12.7"
    runs-on: ${{ matrix.os }}
    needs: authorize
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command
          dir: desktop-app

      - name: Build production bundle
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command
          dir: desktop-app
