name: Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.NAPSE_GITHUB_TOKEN }}
        run: |
          npm install --save-dev semantic-release

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.NAPSE_GITHUB_TOKEN }}
        run: npx semantic-release